Repository final-project-blazing-fox/matching-service, pull requests merged in 2021-09, with the labels that each got.

#2 Add onboarding procedures
  ONBOARDING.md
Labels: documentation

#4 Onboarding Setup
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  README.md
  commitlint.config.js
  package-lock.json
  package.json
  test/api.test.js
Labels: documentation, enhancement

#6 Fix file lint.yml
  .github/workflows/lint.yml
Labels: documentation, enhancement

#8 Fix package.json
  package.json
Labels: documentation, enhancement

#9 Readme codecov badge link edit
  README.md
Labels: documentation, enhancement

#13 Express API Initial Settings
  .env-template
  app.js
  controllers/likes.js
  controllers/matches.js
  db/config.js
  model/index.js
  package-lock.json
  package.json
Labels: enhancement

#14 Set Up REST API and CI Testing
  .env-template
  .github/workflows/node.js.yml
  .prettierignore
  app.js
  controllers/likes.js
  db/config.js
  db/test.json
  jest.config.js
  model/index.js
  model/likes.js
  package-lock.json
  package.json
  server.js
  test.http
  test/api.test.js
  test/likes.test.js
Labels: enhancement

#15 Staging to Dev
  .env-template
  .github/workflows/node.js.yml
  .prettierignore
  README.md
  app.js
  controllers/likes.js
  controllers/matches.js
  db/config.js
  db/test.json
  jest.config.js
  model/index.js
  model/likes.js
  package-lock.json
  package.json
  server.js
  test.http
  test/api.test.js
  test/likes.test.js
Labels: enhancement

#16 GET method for matches
  app.js
  controllers/matches.js
  model/matches.js
  test.http
  test/api.test.js
Labels: enhancement

#19 GCP Cloud Run Deployment Github Workflow
  .dockerignore
  .github/workflows/GCP-Deploy.yml
  .gitignore
  Dockerfile
  package.json
Labels: enhancement

#22 Change GCP Setup Image
  .github/workflows/GCP-Deploy.yml
Labels: bug

#23 Temporarily Remove Image Testing Step
  .github/workflows/GCP-Deploy.yml
Labels: bug

#24 Fix the region of the resource not found in Cloud Run Workflow
  .github/workflows/GCP-Deploy.yml
Labels: bug

#25 Fix port not found in gcloud run deploy
  Dockerfile
Labels: bug

#26 Fix hardcoded port
  server.js
Labels: bug

#27 PATCH and DELETE API method
  .dockerignore
  .github/workflows/GCP-Deploy.yml
  Dockerfile
  Procfile
  app.js
  controllers/likes.js
  db/config.js
  model/likes.js
  package-lock.json
  package.json
  test.http
  test/api.test.js
Labels: enhancement

#30 Add Middleware and Routers, Fix Testing the Rejected Promise
  app.js
  controllers/likes.js
  controllers/matches.js
  middleware/errorHandler.js
  package-lock.json
  package.json
  routers/index.js
  routers/likesRouter.js
  routers/matchesRouter.js
  test.http
  test/api.test.js
Labels: enhancement

#32 Authentication and Authorization
  .env-template
  middleware/authentication.js
  middleware/authorization.js
  middleware/errorHandler.js
  package-lock.json
  package.json
  routers/index.js
  routers/likesRouter.js
  test/api.test.js
Labels: enhancement
